name: Build and Publish Docker Image

on:
  push:
    tags:
      - 'v*'  # Triggers on tags like v1.0, v1.2.3, etc.

permissions:
  contents: read
  packages: write  # Required to push to GHCR

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to GitHub Container Registry (GHCR)
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Extract tag version
        id: vars
        run: echo "TAG_VERSION=${GITHUB_REF#refs/tags/}" >> "$GITHUB_OUTPUT"

      - name: Build and Push Docker Image
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          tags: |
            ghcr.io/${{ github.repository_owner }}/kicad9_auto_custom:${{ steps.vars.outputs.TAG_VERSION }}
            ghcr.io/${{ github.repository_owner }}/kicad9_auto_custom:latest
